language: java
dist: trusty
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-wire.git
- cd vlingo-wire && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-cluster.git
- cd vlingo-cluster && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: d-led
  on:
    branch: master
  key:
    secure: 0HhYQySezqfsFP1fsXnvELAcTgYKLOOvobGDMROk7TV7DU5fUGrDFKORQiNhYEB/2rxkPbhjggX5dIlaCY3hM5qduvVi62S0B62T10oRPwXSYSUu8bP6Gn1GVO9pVb/B/uZc9tJE3XbGdCoHULRq2rTKdvCmH6CSkhEkQg5TGZ5I2xaGJifkWvjy0cd15u+5gt/YqpD7NbpwUXph7Fdqp5oiEr97N1BeYZCP56YnMqYJEzS3C82gZikgj3UPu67e0oxYFro5Qr3gTI1r9IEBvZA25zivB2cYRNPz8p82opmBJSSduvffa0oVY5mTFbrqySOQCBUvVVbq6S7MgSviWAUZm1IXwJNArp1jksda3ZgSo0t4HOA22j+Kk3G0HzYwPloGM6ToC1SmlqQOR+aFqwZIUhxvO05g6NG1GNNcNNXkV6ShLC+U78F+2gzq4AmPq3N+rLj8T8rohwFyV945RxQpasWmup1v22kmhjeeCaoWe5qkEZJlNpqymy2ROHqGJGwrR18/MEBUpR8T/FepcORx29ZY14QNupf84LhxqRCDuc4C4eZirnzbllEGNaNnUqLTwde2IFi/CRTXCJ5uW0qBoBkanN6O9/0QN95CdZaLoF134JYuHrHzkmQEYEPUMvajl9clUL12LU1IFlgmHMhbgwSbifne2abYvmfL7oA=
  passphrase:
    secure: 0Kz/ltzoJgQKsi49WfTa/86TIYaLFxJrqzByNkU61Ri1wDmceNSUKzRTcMUBynfXd91Yml4UQ2ib27G01wUBsOaxFN5NYzXjwxpvlcrascBoZQPBIX9I//lKsXYaCsPeie5D/Z3rFDEfaAkJiSV4SnjZYabYtySYkUA4Nv+ev6Y4X2Zu+AgvBeWMojHL+Tw7wk1BDoMRVC8o8XD5XbL77SRRz1iq/6YbfesO9dllKz4PUcYKof43oeKFhY6h6hLr9QvRdwqGV8keXDHe/MMHyeW+5lV6EGNQWnMgzjS0+agj+v0bHcXTtOYyQBzvo5TQujCXkfgUqWzxzBCivvzT5hBkV3JeCmPOcKacsxdLIYsc2cGiQp4ZzdrQVC3SG3SFp9kiOCmG/IGnI5MoxyevGR7fy5o9E0+AKyL/wThr9lZVbALrAGuPotSi8N4Yc5DDdBZyEV7EroqGlC+sXfKRCDp1UkvMRl9xjn0m1LXYj788rMdXrVPZDS2d3AM/tbfGPz1U5jtTwK8QWJ7wwX8xPjEGhQWUFGwhmQsyPUhU8sK7QXQadz20mmbT06oYHUIKZFmIk+/xkc6yzFE7gF3Oa+H2Uuy0gIgoeRo85pQEmr30G7IfPYRhwuKzO/MQ6kmpnmcS7PGDP13arbyKUkDeaal6uyo+VM09K7D6qvTQr6k=
notifications:
  slack:
    secure: aT/B5sKQn90LVJPQVmR++YfdJ+t4s1mm1A6SMdSaG8hBCPYLv93Cj7OWUASm6l3DbcjighFoGgsYNFxZ7/CCjL0hF0pTpWN8l8p/Dzadx/OZRYagjladbyLqUV3TYj/s7oB8et398Csxa5jN31rFdAjjNC88+UbAml2bU4gGbE8loi4ceZQfG0fUbIGtSc2S21ADAHKSkvXSk8MZzviUF7l6pj4XqF7tbE0T+iieXDPtQWpA2cVtnIQeoe5p/M2CJQqfrFkTXLGLzDcx6bzxZ0+Yh8r8QMDKwHNhdYv9B5mnlpzOdNmsdzKcWYT+Y8tekRhepNmqQFkww3RwBEneesZquaQQME734lmC1EUrcKqcz9B83Zdf5s4fwyL2nAbxSzocp689QLmJzyIeJFpG0AAHS5t634UTSGuwya77UUW9HEuSYkRDJbRmb/LtZR6zozbX9O9h+SxDrN59ZZqwwsZeYKr1SdsEiN/OjcbjmHZckkUCHyRJM6vIrMYwnjf0aIlrLIh+j3yYBHl6Y5lvbngootgFPXzbxmTwbYDd0yF8EsBCoeaacPYbldYdGjvkjk091kAGKlnYTuUE8m16HnETaxWpSN6FkadQODzPvmgL7KFtnt7NB/A4efKCCorhE4pDo/K62Vw8poUyo1OWJyX8LbTHSh8/kCASwvOxQoo=
